### ISSUE TITLE
Automatically fill in missing Fields in persisted file

### ISSUE THREAD

**Issue by zwazel** [umut-sahin/bevy-persistent#33]
Hi, I really like this plugin!
If I change my resource that I want to persist, when a persisted file already exists, it fails to read it. so in the recent update i can make it reverse it to the default, which is nice.
But is it maybe possible to add the new fields with the default value and not reset everything?

For example if my players save their custom keybindings and i then update those keybindings and add new ones, all of their settings would be reset, which is quite annoying :)

**Comment by umut-sahin** [comment]
Hey @zwazel, thanks for you kind words about the plugin!

You can easily achieve this by adding `#[serde(default)]` to your type definition (see https://serde.rs/container-attrs.html#default), which will fill the missing fields from `YourResource::default()`. Here is an example:

```rust
#[derive(Debug, Deserialize, Resource, Serialize)]
#[serde(default)]
struct KeyBindings {
    jump: KeyCode,
    crouch: KeyCode,
}

impl Default for KeyBindings {
    fn default() -> KeyBindings {
        KeyBindings { jump: KeyCode::Space, crouch: KeyCode::C }
    }
}
```

When you use this type, even if the underlying file is completely empty, it'll be parsed as the default value.

Please let me know if this is what you wanted to achieve!

**Comment by zwazel** [comment]
oh amazing, thanks for the quick answer! Thats exactly what I looked for :)
